name: Release

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          bump-patch-for-minor-pre-major: true
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 17
          registry-url: 'https://registry.npmjs.org'

        if: ${{ steps.release.outputs.release_created }}
      - run: npm i && npm run build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm link
        if: ${{ steps.release.outputs.release_created }}
      - run: sern
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
